Use pre-push.d for pre-push hook

diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -1,17 +1,26 @@
-#!/bin/bash
+#!/bin/sh
 
-protected_branch='main'
-current_branch=$(git branch --show-current)
+# This script should be saved in a git repo as a hook file, e.g. .git/hooks/pre-receive.
+# It looks for scripts in the .git/hooks/pre-receive.d directory and executes them in order,
+# passing along stdin. If any script exits with a non-zero status, this script exits.
 
-if [ $protected_branch = $current_branch ]
-then
-  read -p "You're about to push $protected_branch, is that what you intended? [y|n] " -n 1 -r < /dev/tty
-  echo
-  if echo $REPLY | grep -E '^[Yy]$' > /dev/null
-  then
-    exit 0 # push will execute
-  fi
-  exit 1 # push will not execute
-else
-  exit 0 # push will execute
+script_dir=$(dirname $0)
+hook_name=$(basename $0)
+
+hook_dir="$script_dir/$hook_name.d"
+
+if [[ -d $hook_dir ]]; then
+  stdin=$(cat /dev/stdin)
+
+  for hook in $hook_dir/*; do
+    echo "$stdin" | $hook "$@"
+
+    exit_code=$?
+
+    if [ $exit_code != 0 ]; then
+      exit $exit_code
+    fi
+  done
 fi
+
+exit 0
